### ISSUE TITLE
Mobile audio

### ISSUE THREAD

**Issue by therewasaguy** [rosalieyu/Dysturb#1]
- audio isn't playing on ios or android

**Comment by rosalieyu** [comment]
![screen shot 2015-12-12 at 11 07 22 am](https://cloud.githubusercontent.com/assets/5410233/11762782/a79e9b80-a0c0-11e5-936c-8fc79347c44a.png)

**Comment by rosalieyu** [comment]
Commented out 201-253 in index_10.html so the instruction screen goes away for mobile (it's not supposed to be there), here is the error message from safari console.

**Comment by therewasaguy** [comment]
Maybe there should be an instruction screen for mobile so the user has to make a gesture and that gesture can start the audio. I know that doesnt aolve the issue, i may not grt a chance to look at it til tomorrow.
