### ISSUE TITLE
gesture to start audio/video

### ISSUE THREAD

**Issue by therewasaguy** [rosalieyu/Dysturb#10]
some devices need a gesture before playing audio / video. We should start audio/video on the first user gesture.

**Comment by rosalieyu** [comment]
(318-338)
I add load and pause in handle start after the first touch, but android doesn't seem to work.

```
function handleStart(evt) {

    evt.preventDefault();
    moveForward = true;

    // if (!videoIsLoaded) {
    //     videoList[1].load();
    //     videoIsLoaded = true;
    // }
    if (whichMobile == "android_mobile") {
        for (var i = 0; i < videoList.length; i++) {
            videoList[i].load();
            videoList[i].play();
            // videoList[i].pause();

        }
        noTouch = false;

        console.log("touch!");
    }
}
```

**Comment by rosalieyu** [comment]
![screen shot 2015-12-12 at 11 07 22 am](https://cloud.githubusercontent.com/assets/5410233/11762883/3fde9dc6-a0c3-11e5-92b5-eb84cbdf8c98.png)

**Comment by therewasaguy** [comment]
Is this not working for audio or just video?

**Comment by rosalieyu** [comment]
Both, the screenshot is taking from commenting out 203-255 in order to get rid of instruction and blocker when ios first load.

**Comment by rosalieyu** [comment]
141(detecting devices)  is happened before 145 (creating instruction div)
need to try .setTimeout()

**Comment by rosalieyu** [comment]
Landing page/ blocker/ instruction page (supposed to be only for desktop) taken away (fixed) from ios with .setTimeout() function.

**Comment by rosalieyu** [comment]
New error from safari ios console:
[Error] ReferenceError: Can't find variable: i
    _startIOS (audioModule.js, line 99)
    global code (index_10.html, line 129)

**Comment by rosalieyu** [comment]
![screen shot 2015-12-14 at 1 33 53 pm](https://cloud.githubusercontent.com/assets/5410233/11789991/756fdcd4-a267-11e5-8442-8f6404fa7eb2.png)

**Comment by rosalieyu** [comment]
Ios fixed, only andriod still not triggering
